source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BaseTemplateExample' do
 	pod 'Alamofire', '~> 4.0'
	pod 'ObjectMapper', '~> 2.2'
	pod 'SwiftyJSON', '3.1'
	pod 'Kingfisher', '~> 3.1'
end